steps:
  - name: node:10.15.1
    entrypoint: yarn
    args: ['install']
  # - name: gcr.io/cloud-builders/yarn
  #   args: ["test"]
  - name: node:10.15.1
    entrypoint: yarn
    args: ['create-env']
    env:
      - 'COOKIE_SESSION_KEY=${_COOKIE_SESSION_KEY}'
      - 'DISCORD_BOT_SECRET=${_DISCORD_BOT_SECRET}'
      - 'DISCORD_CLIENT_ID=${_DISCORD_CLIENT_ID}'
      - 'DISCORD_CLIENT_SECRET=${_DISCORD_CLIENT_SECRET}'
      - 'DISCORD_GUILD=${_DISCORD_GUILD}'
      - 'DISCORD_GUILD_ID=${_DISCORD_GUILD_ID}'
      - 'DISCORD_REDIRECT=${_DISCORD_REDIRECT}'
      - 'GAE_ENV=${_GAE_ENV}'
      - 'MONGO_DB=${_MONGO_DB}'
      - 'PORT=3001'
  - name: node:10.15.1
    entrypoint: yarn
    args: ['build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.staging.yaml']
timeout: '1600s'
