steps:
  - name: gcr.io/cloud-builders/yarn
    args: ['install']
  # - name: gcr.io/cloud-builders/yarn
  #   args: ["test"]
  - name: gcr.io/cloud-builders/yarn
    args: ['build']
  - name: 'ubuntu'
    args: ['bash', './deploy/create_artifacts.bash']
artifacts:
  objects:
    location: 'gs://buddy-reading-prod-storage/artifacts'
    paths: ['artifact.*\.tar\.gz']
timeout: '1600s'
